---
# @author Anthony Loukinas <anthony.loukinas@redhat.com>

job_templates:
  Ping_With_Survey:
    ask_credential: no
    ask_diff_mode: no
    ask_extra_vars: no
    ask_inventory:  no
    ask_job_type: no
    ask_limit: no
    ask_skip_tags: no
    ask_tags: no
    ask_verbosity: no
    become_enabled: no
    concurrent_jobs_enabled: no
    diff_mode_enabled: no
    fact_caching_enabled: no
    force_handlers_enabled: no
    survey_enabled: yes

    description: "Ping Job Template"
    inventory: "Default Inventory"
    playbook: main.yml
    project: "Ping"
    state: present
    verbosity: 0
    job_type: run

    survey_spec:
      name: ""
      description: ""
      spec:
      - choices:
          - red
          - blue
        default: red
        max: null
        min: null
        new_question: true
        question_description: ''
        question_name: Whats your favorite color?
        required: true
        type: multiplechoice
        variable: favorite_color

  Ping_Without_Survey:
    ask_credential: no
    ask_diff_mode: no
    ask_extra_vars: no
    ask_inventory: yes
    ask_job_type: no
    ask_limit: no
    ask_skip_tags: no
    ask_tags: no
    ask_verbosity: no
    become_enabled: no
    concurrent_jobs_enabled: no
    diff_mode_enabled: no
    fact_caching_enabled: no
    force_handlers_enabled: no
    survey_enabled: no

    description: "Ping Job Template"
    playbook: main.yml
    project: "Ping"
    state: present
    verbosity: 0

project:
  name: Ping
  description: "Ansible Ping Project"
  organization: "default"
  scm_clean: no
  scm_update_on_launch: no
  scm_delete_on_update: no
  scm_credential: ""
  scm_url: "https://github.com/anthonyloukinas/ping.git"