---
# @author Anthony Loukinas <anthony.loukinas@redhat.com>

- hosts: localhost
  gather_facts: no
  tasks:

    - include_role:
        name: tower_api_vars

    - include_role:
        name: main

  module_defaults:
    tower_project:
      tower_username: "{{ tower_username_api }}"
      tower_password: "{{ tower_password_api }}"
      tower_host: "{{ tower_proto_api }}://{{ tower_host_api }}"
      validate_certs: no
    tower_job_template:
      tower_username: "{{ tower_username_api }}"
      tower_password: "{{ tower_password_api }}"
      tower_host: "{{ tower_proto_api }}://{{ tower_host_api }}"
      validate_certs: no