version: '3'

services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - 8089:8080
      - 50000:50000
    volumes:
      - jenkins_home:/var/jenkins_home

networks:
  wf_net:
    external: true

volumes:
  jenkins_home:
    external: true
